# service name follows the otel pattern
service:
  name: "service-name"

app:
  port: 8080
  host: localhost
  timeout: 10s
  cors:
    allowed_origins:
      # allow everything to be able to connect to wsl docker swagger
      - "*"
      # - "http://localhost:9090"
      # - "http://localhost:8080"
    allowed_methods:
      # - "*"
      - POST
      - GET
      - DELETE
      - PUT
      - PATCH
      - HEAD
      - OPTIONS
    allowed_headers:
      # - "*"
      - "Origin"
      - "Content-Type"
      - "Authorization"

logging:
  level: debug
  http_enabled: true

database:
  host: localhost
  port: 5432
  username: pguser
  password: pg123
  db: pismo 
  driver: postgresql


# vim: ts=2 sts=2 sw=2 et
