# service name follows the otel pattern
service:
  name: "service-name"

app:
  port: 8080
  host: localhost
  timeout: 10s
  cors:
    allowed_origins:
      - http://localhost:8080
      - http://localhost:9090
    allowed_methods:
      - POST
      - GET
      - DELETE
      - PUT

logging:
  level: debug
  http_enabled: true

database:
  host: localhost
  port: 5432
  username: pguser
  password: pg123
  db: pismo 
  driver: postgresql


# vim: ts=2 sts=2 sw=2 et
