services:
  database:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: pismo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  openapi:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "9090:8080"
    volumes:
      - ../api:/api
    environment: 
      - SWAGGER_JSON=/api/open_api.spec.yaml

  otel:
    # https://github.com/grafana/docker-otel-lgtm/
    image: grafana/otel-lgtm
    restart: always
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    # environment:
    #   ENABLE_LOGS_GRAFANA: true
    #   ENABLE_LOGS_LOKI: true
    #   ENABLE_LOGS_PROMETHEUS: true
    #   ENABLE_LOGS_TEMPO: true
    #   ENABLE_LOGS_OTELCOL: true
    #   ENABLE_LOGS_ALL: true

volumes:
  pgdata:
