services:
  database:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: pismo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  openapi:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "9090:8080"
    volumes:
      - ../api:/api
    environment: 
      - SWAGGER_JSON=/api/open_api.spec.yaml

volumes:
  pgdata:
